SYMPTOM_MAP = {

# ================= FEVER =================
"fever": "high_fever",
"high fever": "high_fever",
"very high fever": "high_fever",
"temperature": "high_fever",
"body temperature": "high_fever",
"hot body": "high_fever",
"burning body": "high_fever",
"bukhar": "high_fever",
"bukhaar": "high_fever",
"feverish": "high_fever",
"mild fever": "mild_fever",
"low fever": "mild_fever",
"slight fever": "mild_fever",
"on and off fever": "intermittent_fever",
"fever comes and goes": "intermittent_fever",
"night fever": "intermittent_fever",

# ================= COLD / NOSE =================
"cold": "runny_nose",
"cold problem": "runny_nose",
"running nose": "runny_nose",
"runny nose": "runny_nose",
"nose running": "runny_nose",
"water from nose": "runny_nose",
"blocked nose": "congestion",
"nose blocked": "congestion",
"nose jam": "congestion",
"nasal block": "congestion",
"sneezing": "continuous_sneezing",
"continuous sneezing": "continuous_sneezing",
"lot of sneezing": "continuous_sneezing",

# ================= COUGH / BREATH =================
"cough": "cough",
"dry cough": "cough",
"continuous cough": "cough",
"night cough": "cough",
"wet cough": "phlegm",
"cough with mucus": "phlegm",
"phlegm": "phlegm",
"mucus": "phlegm",
"chest congestion": "chest_pain",
"chest pain": "chest_pain",
"pain in chest": "chest_pain",
"breath problem": "breathlessness",
"breathing problem": "breathlessness",
"short breath": "breathlessness",
"shortness of breath": "breathlessness",
# ---------------- HEAD ----------------
"head ache": "headache",
"headache": "headache",
"head pain": "headache",
"pain in head": "headache",
"heavy head": "headache",
"migraine": "headache",

# ---------------- THROAT ----------------
"throat pain": "patches_in_throat",
"pain in throat": "patches_in_throat",
"sore throat": "patches_in_throat",
"throat infection": "patches_in_throat",
"throat irritation": "throat_irritation",
"itchy throat": "throat_irritation",

# ---------------- STOMACH ----------------
"stomach pain": "stomach_pain",
"pain in stomach": "stomach_pain",
"belly pain": "belly_pain",
"abdominal pain": "abdominal_pain",
"gas pain": "passage_of_gases",
"acidity": "acidity",

# ================= THROAT =================
"throat pain": "patches_in_throat",
"sore throat": "patches_in_throat",
"throat infection": "patches_in_throat",
"pain while swallowing": "patches_in_throat",
"throat itching": "throat_irritation",
"itchy throat": "throat_irritation",
"burning throat": "throat_irritation",
"voice problem": "throat_irritation",

# ================= HEAD =================
"headache": "headache",
"head pain": "headache",
"heavy head": "headache",
"migraine": "headache",
"pain behind eyes": "pain_behind_the_eyes",
"eye pain": "pain_behind_the_eyes",
"dizziness": "dizziness",
"giddiness": "dizziness",
"feeling faint": "dizziness",

# ================= BODY PAIN =================
"body pain": "muscle_pain",
"body ache": "muscle_pain",
"muscle pain": "muscle_pain",
"joint pain": "joint_pain",
"joint ache": "joint_pain",
"knee pain": "knee_pain",
"leg pain": "painful_walking",
"pain while walking": "painful_walking",
"back pain": "back_pain",
"lower back pain": "back_pain",
"neck pain": "neck_pain",

# ================= STOMACH =================
"stomach pain": "abdominal_pain",
"belly pain": "belly_pain",
"abdominal pain": "abdominal_pain",
"gas": "passage_of_gases",
"gas problem": "passage_of_gases",
"acidity": "acidity",
"heartburn": "acidity",
"indigestion": "indigestion",
"vomiting": "vomiting",
"throwing up": "vomiting",
"nausea": "nausea",
"loose motions": "diarrhoea",
"diarrhea": "diarrhoea",
"watery stools": "diarrhoea",
"constipation": "constipation",
"hard stools": "constipation",
"loss of appetite": "loss_of_appetite",
"no hunger": "loss_of_appetite",

# ================= URINE =================
"burning urine": "burning_micturition",
"burning while urinating": "burning_micturition",
"pain while urinating": "bladder_discomfort",
"urine pain": "bladder_discomfort",
"frequent urination": "polyuria",
"urine frequently": "polyuria",
"dark urine": "dark_urine",
"smelly urine": "foul_smell_of urine",

# ================= SKIN =================
"itching": "itching",
"skin itching": "itching",
"rashes": "skin_rash",
"skin rash": "skin_rash",
"red spots": "red_spots_over_body",
"white patches": "dischromic _patches",
"fungal infection": "itching",
"ringworm": "itching",
"skin allergy": "skin_rash",
"pimples": "pus_filled_pimples",
"acne": "pus_filled_pimples",

# ================= WEAKNESS =================
"weakness": "fatigue",
"feeling weak": "fatigue",
"tiredness": "fatigue",
"low energy": "lethargy",
"sleepy": "lethargy",

# ================= SWEATING / CHILLS =================
"excess sweating": "sweating",
"night sweats": "sweating",
"shivering": "shivering",
"chills": "chills",

# ================= EYES =================
"red eyes": "redness_of_eyes",
"eye redness": "redness_of_eyes",
"watering eyes": "watering_from_eyes",
"blur vision": "blurred_and_distorted_vision",

# ================= MENTAL =================
"anxiety": "anxiety",
"panic": "anxiety",
"depression": "depression",
"sadness": "depression",
"irritability": "irritability",
"confusion": "altered_sensorium",
"cannot concentrate": "lack_of_concentration",

# ================= OTHER =================
"swelling": "swelling_joints",
"joint swelling": "swelling_joints",
"leg swelling": "swollen_legs",
"face swelling": "puffy_face_and_eyes",
"weight loss": "weight_loss",
"weight gain": "weight_gain",
"yellow eyes": "yellowing_of_eyes",
"yellow skin": "yellowish_skin"
}
